name: Build and Publish WASM

on:
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Build WASM package
        run: |
          wasm-pack build --target nodejs --release --scope pr4j3sh

      - name: Publish to npm
        working-directory: pkg
        run: |
          npm publish --public
